### ISSUE TITLE
2.0 to-do list

### ISSUE THREAD

**Issue by BuffelSaft** [BuffelSaft/pokeemerald#317]
- [ ] Important Trainer teams
- [ ] Fodder trainer teams
- [ ] Rematch trainer teams
- [ ] Wild mons
- [ ] Berry locations
- [ ] New megas
- [ ] Fly
- [ ] New locations
- [ ] New trainers
- [ ] Replace gen 6+ cries with rips, compress where possible

**Comment by BuffelSaft** [comment]
Animations todo:
- [ ] Move_COURT_CHANGE
- [ ] Move_DECORATE
- [x] Move_SNAP_TRAP
- [ ] Move_BEHEMOTH_BLADE
- [ ] Move_BEHEMOTH_BASH
- [ ] Move_SPIRIT_BREAK
- [ ] Move_FALSE_SURRENDER
- [ ] Move_ETERNA_BEAM
- [x] Move_EXPANDING_FORCE
- [ ] Move_STEEL_ROLLER
- [x] Move_SCALE_SHOT
- [x] Move_MISTY_EXPLOSION
- [x] Move_GRASSY_GLIDE
- [x] Move_RISING_VOLTAGE
- [x] Move_SKITTER_SMACK
- [x] Move_LASH_OUT
- [x] Move_POLTERGEIST
~~- [ ] Move_CORROSIVE_GAS~~ Not included
- [x] Move_FLIP_TURN
- [x] Move_TRIPLE_AXEL
- [x] Move_DUAL_WINGBEAT
- [x] Move_SCORCHING_SANDS
- [x] Move_WICKED_BLOW
- [x] Move_SURGING_STRIKES
- [x] Move_THUNDER_CAGE
- [ ] Move_DRAGON_ENERGY
- [x] Move_FREEZING_GLARE
- [x] Move_FIERY_WRATH
- [x] Move_THUNDEROUS_KICK
- [x] Move_GLACIAL_LANCE
- [x] Move_ASTRAL_BARRAGE
- [x] Move_EERIE_SPELL
- [ ] MOVE_FROST_VORTEX
- [ ] MOVE_TOXIN_RUSH
- [ ] MOVE_STONE_CUTTER
- [ ] MOVE_SAND_BLAST
- [x] MOVE_THUNDER_CRASH
- [ ] MOVE_BOULDER_CHARGE
- [ ] MOVE_PSYHORN_SLASH
- [ ] MOVE_ATROCITY
- [x] MOVE_DARTING_BLOW
- [x] MOVE_PINION_VOLLEY

**Comment by BuffelSaft** [comment]
WaitForVBlank fix:
![image](https://github.com/BuffelSaft/pokeemerald/assets/28769716/344bde4e-7d2b-44ac-a9e6-32fd5fd540f6)
